### ISSUE TITLE
IDR_stream CP needs Control Type

### ISSUE THREAD

**Issue by roshankern** [WayScience/IDR_stream#14]
It seems that the CP version of IDR_stream needs `Control Type` in its input metadata dataframe to run.

IDR_stream_cp fails to extract features with the following location metadata:
![image](https://user-images.githubusercontent.com/105665675/218875090-40e7e042-41e5-469d-85e5-d53c1d7aa699.png)
and produces this error in the log:
![image](https://user-images.githubusercontent.com/105665675/218875311-308f82ec-c4cd-4a70-9b8c-192223df67e5.png)

When the location metadata also includes the `Control Type`:
![image](https://user-images.githubusercontent.com/105665675/218877594-510463fa-070d-4f9c-bf53-5f39f42c093a.png)
there is no error produced:
![image](https://user-images.githubusercontent.com/105665675/218877676-ea30e97f-b329-4382-9afd-38e82af569da.png)

This is of course not very good as sometimes a user may want to extract features for cells that have no control type.

**Comment by jenna-tomkinson** [comment]
@roshankern 
 
This error occurs during the “compile_batch_CP_features” as I had coded it to look like the DP output with Mitocheck data. This is very rigid code that I will need to make more flexible to different projects. 

Thank you for finding this!

**Comment by jenna-tomkinson** [comment]
@gwaybio @roshankern 

Just to continue with this issue, I will be making code in a copy of this repo that will change up the RunCellProfiler class and allow for more flexibility where the individual will set the metadata column names into either one of two lists:

1. Metadata that they want to be pushed to the front of the outputted features CSV file 
2. Metadata that want to remove from the outputted features CSV file (e.g. metadata that CellProfiler forces you to have that is not relevant all data (for example, Metadata_Frame) 

This will be something that will be implemented after completing the extraction of Mitocheck CP features as to avoid any unexpected errors.

**Comment by roshankern** [comment]
Sounds good, thanks @jenna-tomkinson! I will keep updating this thread as I attempt to extract CP features for MitoCheck labeled cells.

**Comment by roshankern** [comment]
After formatting the metadata_control locations exactly like the example data for IDR_stream DP, IDR_stream CP seems to have issues compiling the metadata for a run.

The example `data_to_process.tsv` in [example_cp.ipynb] is of format: (https://github.com/WayScience/IDR_stream/blob/main/example_notebooks/example_cp.ipynb) is of format:
![image](https://user-images.githubusercontent.com/105665675/219502467-619278bb-808e-4b91-b209-7ec782f6267e.png)

After simply replacing the text of `data_to_process.tsv` with the desired negative control locations, the new data is of format:
![image](https://user-images.githubusercontent.com/105665675/219502591-ee5bd59d-1e7b-4110-b4a4-965cdeadc7aa.png)

`idrstream_cp.py` is able to extract features, but is unable to compile metadata. The output is shown below:
![image](https://user-images.githubusercontent.com/105665675/219502739-9f46a0a5-7510-4663-a4c0-6a8f834c39a5.png)

**Comment by jenna-tomkinson** [comment]
@roshankern 

What I recommend doing is taking the CellProfiler pipeline and a few example images that will be added to the temporary folder, put it into the GUI, and through the `Metadata` module you should test with the data-to-process file that you input into idrstream and check to see that the metadata is updating properly. What I suspect is something else must have changed, maybe the file names themselves, that is causing the metadata to not compile properly.

Can you confirm that the image file names have not changed, as I have made a specific regular expression that pulls the metadata from the image file names and connects it to the data-to-process metadata file. If that has changed, then I would need to create a new regular expression. I can add this to the documentation as well if this is the case.

**Comment by roshankern** [comment]
It does indeed seem like the `Metadata` module is using the wrong regular expression:
![image](https://user-images.githubusercontent.com/105665675/220186686-10e0489f-bd07-41ac-98e9-570ea1eed334.png)

I am not entirely sure how to read this regular expression but it seems to need `Frames` to `50` to function, which follows with the testing where only the 50th frame works to extract metadata.

**Comment by jenna-tomkinson** [comment]
Great find! This is an easy fix. To explain, this regular expression will only extract metadata from the file names as long as it matches exactly. So you are right, if the file name doesn’t have “50” at the end, no metadata is extracted.

So, as long as the image file names stay the same, then all we need to change is the “50” to [0-9] so that any number at the end of the file name is assigned to the Frames metadata. As well, technically it should be Frame singular (definitely an easy update to make from this first version). 

Let me know if this solves the issue!

**Comment by roshankern** [comment]
Yes, that did seem to solve the issue, thank you!

The `Metadata` module also has this line of code: `Metadata file name:data_to_process.csv`

Does this mean the metadata module is looking for a file named exactly `data_to_process.csv`? If so, that seems like it could easily break in the future... is there a way to not hardcode this?

**Comment by jenna-tomkinson** [comment]
Since there is no metadata flag for the CLI, the pipeline has to reference the exact name of the metadata file that you will be using, and it has to be located in the same place as the images directory. So, there is no way to not hardcode this unless we dig into the CellProfiler CLI and make the change in a PR for them.

**Comment by roshankern** [comment]
Got it, thank you for the clarification!

I am still a little confused about how this pathing works...
the `.cpipe` file that contains the `Metadata` module is inside `example_notebooks/example_files/CP_files`
and the `example_cp.ipynb` notebook that runs the code is at `example_notebooks`.

How does CellProfiler know where to find the `data_to_process.csv` without an exact path? Does it look through the subdirectories? I would think it would want a location from where the notebook is running (i.e. `example_files/CP_files/data_to_process.csv`)

**Comment by jenna-tomkinson** [comment]
Here is what the GUI shows for the metadata file:

![image](https://user-images.githubusercontent.com/107513215/220398345-b72cf4e5-e2fa-46df-b645-163bf5327183.png)

As you can see, I have the metadata file location set to the Default Input Location. This allows for CellProfiler not to get stuck on having specific pathing because when using the CLI, it will take that path I set for the metadata in the GUI and add it onto the path I have for the images directory for the CLI (e.g,. an example is that it will make the metadata file path as /home/jenna/GitHub/IDR_stream/tmp/images/Desktop/GitHub/IDR_stream/example_notebooks/example_files/...). 

So based on this pathing issue, I figured out that when using the CLI, it is assumed that your metadata file is contained within the images directory. 

Within the `CP_idr.py` file, the [copy_CP_files function](https://github.com/WayScience/IDR_stream/blob/c632e5861fabb7003343ce7259c74fe6237d0356/idrstream/CP_idr.py#L124) will copy the `data_to_process.csv` file to the images directory of the CellProfiler project (e.g., tmp/CP_Project/images). This allows CellProfiler to run based on the constraints of not having a metadata flag.  

In all, that means CellProfiler (or the `.cppipe` pipeline) only knows where the metadata file is if it is located in the images directory which is set in the `prepare_batch` function.

**Comment by roshankern** [comment]
Ahhhh, thanks for the clarification!
